### ISSUE TITLE
[variable]Avoid using var

### ISSUE THREAD

**Issue by koji** [emilylin-itp/solar#1]
Let's use let instead of var.
I found var in your code.
https://github.com/emilylin-itp/solar/blob/master/120418_solar_serial_input_v1/sketch.js

Please check `All You Code` (sketch.js and js code you wrote)

**Comment by elinsterz** [comment]
great, thanks so much. just changed: https://github.com/emilylin-itp/solar/blob/master/120418_solar_serial_input_v1/sketch.js
