### ISSUE TITLE
[page move] sample code

### ISSUE THREAD

**Issue by koji** [emilylin-itp/solar#2]
```
if (buttonA === 1) {
  window.location.href="buttonA.html";
}
```

**Comment by koji** [comment]
`check file path`
use chrome dev tool. if you see `404`, chrome can't find a file.

**Comment by elinsterz** [comment]
@sleepy-maker 
I tried your above code 
`" if (buttonA === 1) {
  window.location.href="buttonA.html";
}"`
works great on my laptop's browswer. however the buttons don't switch the page on the ipad like it does on my laptop. the ipad is connected via local host and all the webpage shows up, but it doesn't react to the button press function.  so i don't think the logic is wrong, but perhaps the code to connect properly via local host is wrong:
what do you think is the issue?

i think it has to do with these lines of code that I have on all the js pages that new to switch when a button is pressed but not sure:

 `  if (button1 == 1) {
    window.location.href = "../index.html";
  }
  if (button2 == 1) {
    window.location.href = "animate.html";
  }
  if (button3 == 1) {
    window.location.href = "voltGen.html";
  }
  if (button4 == 1) {
    window.location.href = "battery2.html";
  }
  if (rightBar == 1) {
    window.location.href = "battery.html";
  }`


sharing with you the link to the p5js code:
the p5js code is now linked to arduino via serialport connector. functioning code is here: https://github.com/emilylin-itp/solar/tree/master/full_solar_site_serial

also sharing with you the link to the arduino code: 
https://github.com/emilylin-itp/solar/blob/master/120918_arduino_full_code_v1/120918_Full_code_v1.ino

**Comment by elinsterz** [comment]
@sleepy-maker 
for clarity, also sharing with you a video that demonstrates how the buttons interact with web page.

[https://vimeo.com/305439571](url)

**Comment by koji** [comment]
@emilylin-itp 
`the ipad is connected via local host`
Could you tell me what you did exactly?
I guess you are using Safari to do something on iPad. Unfortunately, iOS is totally different from macOS which means there are some limitations on browser. In addition, iOS is stricter than Android OS.

Can you do the same thing with Chrome?

**Comment by elinsterz** [comment]
@sleepy-maker 
`the ipad is connected via local host` = i used “python -m SimpleHTTPServer” in the terminal. Then open a tab and type “localhost:8000” for the address to get access to the webpage. on ipad i used “ID address:8000” instead. made sure the device share the same local internet with the laptop. 

thanks for the suggestion, just downloaded chrome on the ipad but i don't think it's working for chrome either. but i'm not sure why. any thoughts or suggestions? 

p.s. thank you so much for helping out like this, so grateful.

**Comment by koji** [comment]
@emilylin-itp 
you may want to try https://hammerjs.github.io/

**Comment by elinsterz** [comment]
@sleepy-maker 
tried to add to this hammer.js to my index.html using this code: `  <script src="hammer.js"></script>`
but i don't think it's working. am i doing this properly?

**Comment by elinsterz** [comment]
@sleepy-maker are you available/ in the 3rd floor room any time today by any chance? no worries if not, remote works great too.

**Comment by koji** [comment]
@emilylin-itp Are you sure that you are using the right file path? `hammer.js` is the same dir as well as `index.html`?
hammer.js allows us to add smartphone motion(swipe, tap etc).
Of course, you need to code.

**Comment by elinsterz** [comment]
@sleepy-maker yes in the same dir as index.html. right now. i can change to be in the "js" folder. ah i see, i will follow the coding steps on this page: https://hammerjs.github.io/getting-started/
right? 
it says to add: `var hammertime = new Hammer(myElement, myOptions);
hammertime.on('pan', function(ev) {
	console.log(ev);
});`

**Comment by koji** [comment]
@emilylin-itp yeah, i think in your case, you need to use `tap`

**Comment by koji** [comment]
recommend you to remove the following lines

https://github.com/emilylin-itp/solar/blob/master/full_solar_site_serial/index.js#L53-L56

**Comment by koji** [comment]
Chrome dev tool has an emulator function like the following. it might be helpful to debug your code.

open dev tool --> click tablet/smartphone icon that next `Elements` tag

<img width="1591" alt="screen shot 2018-12-10 at 3 44 49 pm" src="https://user-images.githubusercontent.com/474225/49760502-a5176a00-fc92-11e8-94c5-558bd310de46.png">
